### PR TITLE
extend Monte-Carlo valuation to general contracts

### PR DESCRIPTION
**Pull request by drsk0**
This extends the Monte-Carlo model to be able to price all well-formed contracts. The abstract model is extended as well. The implementation seems straightforward, but I'd really appreciate a review from someone with more financial experience than me.

It would be nice to add some golden tests for this. I'm happy to add them if you could provide me with contracts for which the value has been determined with a correct MC implementation.

### CODE REVIEW

**Comment by aviks** [comment]
Nice, this looks good. As you say, would be good to add some tests to this before merging.

**Comment by drsk0** [comment]
Great! I'll try to find contracts without analytic solutions for which the valuation is known and add them to the golden tests. Let me know if you have any examples that you'd like to add.

**Comment by drsk0** [comment]
Would you be happy with just golden tests? To get some ground truth in this case proves to be more complicated than I thought, I would somehow have to get access to contracts and their valuation, for which I also know the correct model implementation in Miletus.

**Comment by drsk0** [comment]
Closing this PR for the time being due to inactivity.

**Pull request closed without merging**
